# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_A', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exch1', models.CharField(max_length=20)),
                ('exch2', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=20)),
            ],
        ),
    ]
